puts "How many hours are you at school?"
hours = gets.to_i  "7"
puts "How many classes do you have?"
classes = gets.to_i  "7"
puts "How many days do you have school in one week?"
days = gets.to_i  "5" 
